[project]
name = "streamlit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=0.1.0",
    "streamlit-authenticator>=0.4.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
